tartak_app/tartak_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='zamowienia/')),
    path('zamowienia/', include('order_display.urls', namespace='order_display')),
    path('login/', include('users.urls', namespace = 'users')),
    path('worker/',include('worker_app.urls', namespace = 'worker_app')),
]

tartak_app/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#from.views import login_view
app_name = "users"
urlpatterns = [
    path('',views.login_view, name='login'),
    path('logout/', views.logout_view, name = 'logout')
]

tartak_app/worker_app/urls.py
from django.urls import path
from . import views

app_name = 'worker_app'
urlpatterns = [
   path('', views.order_list, name='order_list'),
   path('<slug:order>/', views.order_detail, name = 'order_detail')
]

tartak_app/worker_app/models.py
from django.db import models

# Create your models here.

tartak_app/worker_app/views.py
from django.shortcuts import render
from order_display.models import Order, Element
from django.contrib.auth.models import User 
# Create your views here.

def order_list(request):
    worker = request.user
    orders = Order.objects.filter(workers = worker)
    return render(request, 'worker_app/order_list.html', {'orders':orders})

def order_detail(request, order):
    order = Order.objects.get(slug = order)
    elements = order.element.all()
    return render(request, 'worker_app/order_detail.html', {'order':order, 'elements':elements})

tartak_app/worker_app/templates/worker_app/order_detail.html
{% extends "order_display/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Szczegóły zamówienia{% endblock %}
{% block content %}



  <section class="vh-100" style="background-color: #eee;">
    <div id='order_info'>
    <tr class="inner-box">
      <th scope="row">
          <div class="event-date">
              {{order.due}}
          </div>
      </th>
      <td>
          <div class="event-wrap">
              <h3><a>{{ order.client }}</a></h3>
              <div class="meta">
                  <div class="organizers">
                      <a>{{order.adres}}</a>
                  </div>
                  <div class="categories">
                      <a>{{order.status}}</a>
                  </div>
              </div>
          </div>
      </td>
    </div>
    <div class="container py-5 h-100">
      <div style="margin-left: auto; margin-right: auto; width: fit-content;">
    </div>
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">Elementy</h4>
              <table class="table mb-0">
                <tbody>
                  {% for element in elements %}
                  <tr>
                    {% if element.status == element.Status.IN_PROGRESS %}
                      <td>{{element.name}}</td>
                      <td>{{element.width}}x{{element.height}}x{{element.length}}</td>
                      <td>{{element.volume}}m3</td>
                    {% endif %}
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>
  {% comment %}  {% endcomment %}
{% endblock %}

tartak_app/worker_app/templates/worker_app/order_list.html
{% extends "order_display/base.html" %}
{% block title %}Lista zamówień{% endblock %}

{% block content %}
<div class="event-schedule-area-two bg-color pad100">
  <div class="container">
      <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade active show" id="home" role="tabpanel">
              <div class="table-responsive">
                  <table class="table">
                    {% for order in orders %}
                      <tr class="inner-box">
                          <th scope="row">
                              <div class="event-date">
                                  {{order.due}}
                              </div>
                          </th>
                          <td>
                              <div class="event-wrap">
                                  <h3><a>{{ order.client }}</a></h3>
                                  <div class="meta">
                                      <div class="organizers">
                                          <a>{{order.adres}}</a>
                                      </div>
                                      <div class="categories">
                                          <a>{{order.status}}</a>
                                      </div>
                                  </div>
                              </div>
                          </td>
                          <td>
                              <div class="primary-btn">
                                  <a class="btn btn-primary" href={% url 'worker_app:order_detail' order.slug %}>Szczegóły</a>
                              </div>
                          </td>
                      </tr>
                      {% endfor %}
                  </table>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}