tartak_app/order_display/urls.py
from django.urls import path
from . import views

app_name = 'order_display'
urlpatterns = [
    path('', views.OrderListView.as_view(), name = "order_list"),
    path('szczegoly/<slug:order>/', views.order_detail_view, name = 'order_detail'),
    path('klient/<slug:client>/', views.client_detail_view, name = 'client_detail'),
    path('edit/<slug:element>', views.element_edit_view, name = 'element_edit'),
    path('nowe/', views.new_order, name = 'new_order'),
    path('show_searches/', views.show_searches, name='show_searches'),
    path('finnish_element/<slug:element>', views.finnish_element, name='finnish_element'),
    path('finnish_order/<slug:order>', views.finnish_order, name='finnish_order'),
    path('archiwum/', views.Archive.as_view(), name ="archiwum"),
    path('brudnopis/', views.Draft.as_view(), name ="brudnopis"),
]

tartak_app/tartak_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='zamowienia/')),
    path('zamowienia/', include('order_display.urls', namespace='order_display')),
    path('login/', include('users.urls', namespace = 'users')),
    path('worker/',include('worker_app.urls', namespace = 'worker_app')),
]

tartak_app/users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#from.views import login_view
app_name = "users"
urlpatterns = [
    path('',views.login_view, name='login'),
    path('logout/', views.logout_view, name = 'logout')
]

tartak_app/order_display/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from unidecode import unidecode
from django.urls import reverse
from django.contrib.auth.models import User

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status = Order.Status.PUBLISHED)


class Client(models.Model):
    first_name = models.CharField(max_length=20,blank=True)
    last_name = models.CharField(max_length=20,blank=True)
    phone_number = models.IntegerField(blank = True)
    slug = models.SlugField(max_length=255,blank=True, unique=True)
    
    def __str__(self):
        return self.last_name
    
    def get_absolute_url(self):
        return reverse("client_detail", kwargs={"slug": self.slug})
    
    def save(self, *args, **kwargs):
        if not self.slug:
            if not Client.objects.all():
                next_id = 1
            else:
                next_id = Client.objects.order_by('-pk').first().pk + 1
            self.slug = slugify(unidecode(f"{next_id}_{self.first_name}_{self.last_name}"))
        super(Client, self).save(*args, **kwargs)


    
    
class Order(models.Model):
    objects = models.Manager()
    published = PublishedManager()
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
        FINISHED = 'FI', 'Finished'
    client = models.ForeignKey(Client,
                               on_delete=models.CASCADE,
                               related_name='order',
                               blank = True)
    created = models.DateField(default = timezone.now)
    due = models.DateField(default = timezone.now, blank=True)
    slug = models.SlugField(max_length=255, blank=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.PUBLISHED)
    adres = models.CharField(max_length=255, blank=True)
    workers = models.ManyToManyField(User)
    def __str__(self):
        return self.status
    
    def get_absolute_url(self):
        return reverse("order_display:order_detail", args=[self.slug])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            if not Order.objects.all():
                next_id = 1
            else:
                next_id = Order.objects.order_by('-pk').first().pk + 1
            self.slug = slugify(unidecode(f"{next_id}_{self.due}"))
        super(Order, self).save(*args, **kwargs)
    


class Element(models.Model):
    class Units(models.TextChoices):
        SZTUKI = 'szt'
        M3 = 'm3'
        MB = 'mb'
    class Status(models.TextChoices):
        DONE = 'zrobione'
        IN_PROGRESS = 'do zrobienia'
    name = models.CharField(max_length=20, blank=True)
    width = models.FloatField(blank=True)
    height = models.FloatField(blank=True)
    length = models.FloatField(blank=True)
    count = models.IntegerField(blank=True)
    volume = models.FloatField(blank=True)
    unit = models.CharField(max_length=3,
                              choices=Units.choices,
                              default=Units.M3)
    status = models.CharField(max_length = 12,
                              choices = Status.choices,
                              default = Status.IN_PROGRESS)
    description = models.TextField(blank = True)
    order = models.ForeignKey(Order,
                              on_delete=models.CASCADE,
                              related_name='element')
    slug = models.SlugField(max_length=255)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("order_display:order_detail", args=[self.slug])
    
    def save(self, *args, **kwargs):
        if self.unit==self.Units.SZTUKI:
            self.volume = self.width*self.height*self.length*self.count/1000000
        elif self.unit==self.Units.MB:
            self.volume = self.width*self.height*self.length*(self.length/self.count)/1000000
        else:
            self.volume = self.count
            
        if not self.slug:
            if not Element.objects.all():
                next_id = 1
            else:
                next_id = Element.objects.order_by('-pk').first().pk + 1
            self.slug = slugify(unidecode(f"{next_id}_{self.name}"))
        
        super(Element, self).save(*args, **kwargs)
    

tartak_app/order_display/forms.py
from django import forms
from .models import Element, Order, Client
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Field, Div
from searchableselect.widgets import SearchableSelect

class ElementForm(forms.ModelForm):
    element_form = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model=Element
        fields = ['element_form','name', 'width', 'height', 'length','count', 'description','unit']
        widgets = {
            'unit': forms.RadioSelect(),
        }
    unit = forms.ChoiceField(choices=Element.Units),
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            "element_form",
            'name',
            Row(
                'unit',
                Field('count', id="amount"),
                ),
            Row(
                Column('width', css_class='form-group col-md-4 mb-0'),
                Column('height', css_class='form-group col-md-4 mb-0'),
                Column('length', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Submit('submit', 'Zatwierdź')
        )
    
class OrderForm(forms.ModelForm):
    order_form = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    class Meta:
        model=Order
        fields = ['order_form','status','due','adres', 'workers']
        
        widgets = {
            'workers': forms.CheckboxSelectMultiple,
            'due':forms.DateInput(attrs={'type': 'date'}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Div(css_id = "client_searches_div"),
            'order_form',
            'adres',
            Field('workers',id="workers"),
            Row(
                Column('status', css_class='form-group col-md-4 mb-0'),
                Column('due', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
        )
        
        
class ClientForm(forms.ModelForm):
    class Meta:
        model=Client
        fields = ['first_name','last_name','phone_number']
        widgets = {
                'first_name':forms.TextInput(attrs={'css_id': 'client_first_name'}),
                'last_name':forms.TextInput(attrs={'id': 'client_last_name'}),
                'phone_number':forms.TextInput(attrs={'id': 'client_phone_number'}),
            }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-4 mb-0'),
                Column('last_name', css_class='form-group col-md-4 mb-0'),
                Column('phone_number', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
        )

tartak_app/order_display/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import Element, Order, Client
from .forms import ElementForm, OrderForm, ClientForm
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import JsonResponse
from django.db.models import Q


class OrderListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    queryset = Order.published.all()
    context_object_name = 'orders'
    template_name = 'order_display/order_list.html'

@login_required(login_url='/login/')   
def order_detail_view(request, order):
    order = Order.objects.get(slug=order)
    elements = order.element.all().order_by('status')
    if request.method == "POST":
        if 'element_form' in request.POST:
            element_form = ElementForm(request.POST)
            order_form = OrderForm()
            if element_form.is_valid():
                element = element_form.save(commit=False)
                element.order = order
                element.save()
        if 'order_form' in request.POST:
            order_form = OrderForm(request.POST, instance = order)
            element_form = ElementForm()
            if order_form.is_valid():
                order = order_form.save()
        return redirect(order.get_absolute_url())
    else:
        element_form = ElementForm()
        order_form=OrderForm(instance = order)
        

    return render(request, 'order_display/order_detail.html', {"order":order,"elements":elements, "element_form": element_form,'order_form':order_form})
    
@login_required(login_url='/login/')
def client_detail_view(request, client):
    client = Client.objects.get(slug = client)
    orders = client.order.all()
    return render(request, 'order_display/client.html', context={"client":client, "orders": orders})

@login_required(login_url='/login/')
def element_edit_view(request, element):
    element = Element.objects.get(slug = element)
    if request.method=='POST':
        element_form = ElementForm(request.POST, instance=element)
        if element_form.is_valid():
            element.save()
            return redirect(element.order.get_absolute_url())
    else:
        element_form = ElementForm(instance=element)
        
    return render(request, 'order_display/element_edit.html', {'element_form': element_form})


def new_order(request):
    if request.method=='POST':
        form = OrderForm(request.POST)
        client_form = ClientForm(request.POST)
        if form.is_valid() and client_form.is_valid():
            messages.success(request, "utworzono nowe zamówienie")
            order = form.save(commit=False)
            client = client_form.save(commit=False)
            if client.first_name or client.last_name or client.phone_number:
                exists = Client.objects.filter(first_name = client.first_name).filter(last_name=client.last_name)
                if exists:
                    order.client = exists[0]
                else:
                    client.save()
                    order.client = client
                print(order.client)
            order.save()
            return redirect(order.get_absolute_url())
        else:
            if client_form.is_valid():
                print('cos nie tak')
            messages.error(request, "coś poszło nie tak")
            return render(request, 'order_display/new_order.html', {'form': form, "client_form":client_form})
    form = OrderForm()
    client_form = ClientForm()
    return render(request, 'order_display/new_order.html', {'form': form, "client_form":client_form})


def show_searches(request):
    data = request.GET['search']
    print(data)
    searches = Client.objects.filter(
        Q(first_name__contains=data) | 
        Q(last_name__contains=data)
    )
    searches = list(searches.values())
    return JsonResponse({'searches':searches})


def finnish_element(request, element):
    element = Element.objects.get(slug = element)
    if element.status == Element.Status.DONE:
        element.status = Element.Status.IN_PROGRESS
    else: 
        element.status = Element.Status.DONE
    element.save()
    return redirect(element.order.get_absolute_url())

def finnish_order(request, order):
    order = Order.objects.get(slug = order)
    if order.status == Order.Status.PUBLISHED:
        order.status = Order.Status.FINISHED
    else: 
        order.status = Order.Status.PUBLISHED
    order.save()
    return redirect(order.get_absolute_url())


class Archive(LoginRequiredMixin, ListView):
    login_url = '/login/'
    queryset = Order.objects.filter(status = Order.Status.FINISHED)
    context_object_name = 'orders'
    template_name = 'order_display/order_list.html'

class Draft(LoginRequiredMixin, ListView):
    login_url = '/login/'
    queryset = Order.objects.filter(status = Order.Status.DRAFT)
    context_object_name = 'orders'
    template_name = 'order_display/order_list.html'
    

tartak_app/order_display/templates/order_display/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load crispy_forms_tags %}
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <link rel="stylesheet" href="{% static 'css/list_css.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/navbar_css.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/order_detail.css' %}" type="text/css" />
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark p-3 bg-secondary" id="headerNav">
    <div class="container-fluid">
      <a class="navbar-brand d-block d-lg-none" href="#">
        <img src="/static_files/images/logos/logo_2_white.png" height="80" />
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav mx-auto ">
        {% if user.groups.all %}
          {% for group in user.groups.all %}
            {% if group.name == 'manager' %}
          
            <li class="nav-item">
              <a class="nav-link mx-2 active" aria-current="page" href="{% url "order_display:order_list" %}">Zamówienia</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2 active" href="{% url "order_display:archiwum" %}">Archiwum</a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2 active" href="{%url "order_display:brudnopis" %}">Brudnopis</a>
            </li>
            <li class = "nav_item">
              <input class="form-control mr-sm-2 dropdown-toggle " type="search" placeholder="Search" aria-label="Search" id='searchbar'>
              <ul class="list-group position-absolute z-3" id = "dropdown">
                
              </ul>
            </li>
          {% endif %}
        {% endfor %}
      {% endif%}
          {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.username }}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item active" href="{% url 'users:logout' %}">Wyloguj</a></li>
              </ul>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
    
  </nav>



{% comment %} ----------------------------------------   {% endcomment %}
<div class="container">
  {% for message in messages %}
<div class="container-fluid p-0">
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    {{ message }}
  </div>
</div>
{% endfor %}
  {% block content %}
  {% endblock %}


</div>
</body>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    setInterval(function(){
      search = document.getElementById('searchbar').value;
      if(search.length!=0){
        $.ajax({
          type:'GET',
          url:"{% url 'order_display:show_searches' %}",
          data: {"search":search},
          success: function(response){
            $("#dropdown").empty();
            for(var key in response.searches){
              console.log(response.searches[key].first_name);
              var temp = `<a href = http://127.0.0.1:8000/zamowienia/klient/${response.searches[key].slug}><li class="list-group-item" style="z-index: 999;"> ${response.searches[key].first_name} ${response.searches[key].last_name} </li></a>`;
              $("#dropdown").append(temp);
            }
          },
          error: function(response){
            console.log("huj");
          },
        });
      }
      else{
        $("#dropdown").empty();
      }
    },1000);
  });
</script>



</html>

tartak_app/order_display/templates/order_display/client.html
{% extends "order_display/base.html" %}
{% block title %}Lista zamówień{% endblock %}

{% block content %}
<div class="event-schedule-area-two bg-color pad100">
    <div id='order_info'>
        <tr class="inner-box">
          <th scope="row">
          </th>
          <td>
              <div class="event-wrap">
                  <h3><a>{{ client.first_name }} {{client.last_name}}</a></h3>
                  <div class="meta">
                      <div class="organizers">
                          <a>tel. {{client.phone_number}}</a>
                      </div>
                  </div>
              </div>
          </td>
        </tr>
        </div>
  <div class="container">
      <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade active show" id="home" role="tabpanel">
              <div class="table-responsive">
                  <table class="table">
                    {% for order in orders %}
                      <tr class="inner-box">
                          <th scope="row">
                              <div class="event-date">
                                  {{order.due}}
                              </div>
                          </th>
                          <td>
                              <div class="event-wrap">
                                  <h3><a>{{ order.client }}</a></h3>
                                  <div class="meta">
                                      <div class="organizers">
                                          <a>{{order.adres}}</a>
                                      </div>
                                      <div class="categories">
                                          <a>{{order.status}}</a>
                                      </div>
                                  </div>
                              </div>
                          </td>
                          <td>
                              <div class="primary-btn">
                                  <a class="btn btn-primary" href={% url 'order_display:order_detail' order.slug %}>Szczegóły</a>
                              </div>
                          </td>
                      </tr>
                      {% endfor %}
                  </table>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

tartak_app/order_display/templates/order_display/element_edit.html
{% extends "order_display/base.html" %}
{% load crispy_forms_tags %}
dupsko eheh
{% block content %}
    <form method="post">
        {% csrf_token %}
        {% crispy element_form %}
    </form>
{% endblock content %}

tartak_app/order_display/templates/order_display/new_order.html
{% extends "order_display/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Nowe zamówienie{% endblock %}
{% block content %}

<form method="POST"  autocomplete="off">
    {% csrf_token %}
    {% crispy client_form %}
    {% crispy form %}
    <input type="Submit">
</form>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
  function chose_client(first_name, last_name, phone_number){
    document.getElementById('id_first_name').value = first_name;
    document.getElementById('client_last_name').value = last_name;
    document.getElementById('client_phone_number').value = phone_number;
    return(0);
  }
  $(document).ready(function(){
    $("#client_searches_div").append('<ul class="list-group position-absolute z-3" id = "client_searches"></ul>');
    setInterval(function(){
      search = document.getElementById('id_first_name').value;
      console.log(search)
      if(search.length!=0){
        $.ajax({
          type:'GET',
          url:"{% url 'order_display:show_searches' %}",
          data: {"search":search},
          success: function(response){
            $("#client_searches").empty();
            for(var key in response.searches){
              console.log(response.searches[key].first_name);
              var temp = `<button type="button" onclick="chose_client('${response.searches[key].first_name}', '${response.searches[key].last_name}', ${response.searches[key].phone_number})"><li class="list-group-item" style="z-index: 999;"> ${response.searches[key].first_name} ${response.searches[key].last_name} </li></button>`;
              $("#client_searches").append(temp);
            }
          },
          error: function(response){
            console.log("nie działa");
          },
        });
      }
      else{
        $("#client_searches").empty();
      }
    },1000);
  });

</script>


{%endblock content%}

tartak_app/order_display/templates/order_display/order_detail.html
{% extends "order_display/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Szczegóły zamówienia{% endblock %}
{% block content %}



  <section class="vh-100" style="background-color: #eee;">
    <div id='order_info'>
    <tr class="inner-box">
      <th scope="row">
          <div class="event-date">
              {{order.due}}
          </div>
      </th>
      <td>
          <div class="event-wrap">
              <h3><a>{{ order.client }}</a></h3>
              <div class="meta">
                  <div class="organizers">
                      <a>{{order.adres}}</a>
                  </div>
                  <div class="categories">
                      <a>{{order.status}}</a>
                  </div>
              </div>
          </div>
      </td>
    </div>
    <div class="container py-5 h-100">
      <div style="margin-left: auto; margin-right: auto; width: fit-content;">
        <button id="show_order_form" class='btn btn-primary'>Edytuj szczegóły zamówienia</button>
        <div id='order_form' style="display: none;">
            <form method="post">
                {% csrf_token %}
                {% crispy order_form %}
                <input type=Submit>
            </form>
        </div><br>
    </div>
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3">
            <div class="card-body p-4">
              <h4 class="text-center my-3 pb-3">Elementy</h4>
              <table class="table mb-0">
                <tbody>
                  {% for element in elements %}
                  <tr>
                    <td>{{element.name}}</td>
                    <td>{{element.width}}x{{element.height}}x{{element.length}}</td>
                    <td>{{element.volume}}m3</td>
                    <td class = 'float-right'>
                      {% if element.status == element.Status.IN_PROGRESS %}
                        <a href = "{% url 'order_display:element_edit' element.slug %}"><button class="btn btn-warning float-right">Edytuj</button></a>
                        <a href = "{% url 'order_display:finnish_element' element.slug %}"><button class="btn btn-danger float-right">Zakończ</button></a>
                      {% else %}
                        <a href = "{% url 'order_display:finnish_element' element.slug %}"><button class="btn btn-secondary float-right">Cofnij zakończenie</button></a>
                      {% endif %}
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
              <button id="show_element_form" class='btn btn-primary'>dodaj element</button>
                  <div id = "new_element_form" style="display:none;">
                  <form method="post">
                      {% csrf_token %}
                      {% crispy element_form %}
                  </form>
                  </div>
            </div>
          </div>
          <td class = 'float-right'>
            {% if order.status == order.Status.PUBLISHED %}
              <a href = "{% url 'order_display:finnish_order' order.slug %}"><button class="btn btn-danger float-right">Zakończ zamówienie</button></a>
            {% else %}
              <a href = "{% url 'order_display:finnish_order' order.slug %}"><button class="btn btn-secondary float-right">Cofnij zakończenie zamówienia</button></a>
            {% endif %}
          </td>
        </div>
      </div>
    </div>

  </section>
  {% comment %}  {% endcomment %}
<script>
    document.getElementById("show_order_form").onclick = function() {show_order_form()};
    function show_order_form() {     
        document.getElementById("order_form").style.display = "block";
        document.getElementById("show_order_form").style.display = "none";
        document.getElementById("order_info").style.display = "none";
    }
    document.getElementById("show_element_form").onclick = function() {show_element_form()};
    function show_element_form() {
        document.getElementById("new_element_form").style.display = "block";
        document.getElementById("show_element_form").style.display = "none";
    }
</script>

{% endblock %}

tartak_app/order_display/templates/order_display/order_list.html
{% extends "order_display/base.html" %}
{% block title %}Lista zamówień{% endblock %}

{% block content %}
<div class="event-schedule-area-two bg-color pad100">
  <div class="container">
      <div class="tab-content" id="myTabContent">
          <div class="tab-pane fade active show" id="home" role="tabpanel">
              <div class="table-responsive">
                  <table class="table">
                    {% for order in orders %}
                      <tr class="inner-box">
                          <th scope="row">
                              <div class="event-date">
                                  {{order.due}}
                              </div>
                          </th>
                          <td>
                              <div class="event-wrap">
                                  <h3><a>{{ order.client }}</a></h3>
                                  <div class="meta">
                                      <div class="organizers">
                                          <a>{{order.adres}}</a>
                                      </div>
                                      <div class="categories">
                                          <a>{{order.status}}</a>
                                      </div>
                                  </div>
                              </div>
                          </td>
                          <td>
                              <div class="primary-btn">
                                  <a class="btn btn-primary" href={% url 'order_display:order_detail' order.slug %}>Szczegóły</a>
                              </div>
                          </td>
                      </tr>
                      {% endfor %}
                  </table>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

tartak_app/order_display/templates/order_display/searchbar.html
{% comment %} 
  <div class="dropdown">
    <input class="form-control mr-sm-2 dropdown-toggle" type="search" placeholder="Search" aria-label="Search" id='searchbar'>
    <ul class="list-group" id = "dropdown">
      
    </ul>

  </div>

   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
  $(document).ready(function(){
    setInterval(function(){
      search = document.getElementById('searchbar').value;
      if(search.length!=0){
        $.ajax({
          type:'GET',
          url:"{% url 'order_display:show_searches' %}",
          data: {"search":search},
          success: function(response){
            $("#dropdown").empty();
            for(var key in response.searches){
              console.log(response.searches[key].first_name);
              var temp = `<li class="list-group-item"> <a href = '${response.searches[key].slug}'>${response.searches[key].first_name} ${response.searches[key].last_name} </a></li>`;
              $("#dropdown").append(temp);
            }
          },
          error: function(response){
            console.log("huj");
          },
        });
      }
      else{
        $("#dropdown").empty();
      }
    },1000);
  });
</script> {% endcomment %}